name: Build and Push to Docker Hub
on:
  [workflow_dispatch]
  
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name : Build the Docker image
        run: docker build ./dind/ --file Dockerfile -t victorbecerra/dind:latest
      - name: Push docker image to Hub
        run: |
          docker login -u victorbecerra -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push victorbecerra/dind:latest
